#!/usr/bin/env bash
#Install Nginx on my web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello Wolrd!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
