#!/usr/bin/env bash
#Debug issue why nginx keeping container from listin port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
