#!/usr/bin/env bash
#Used to print Best school 10 times but Hi
#instead of best school on iteration 9
#using while loop

a=0
while [ $a -lt 10 ];
do
	if [ $a -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best school"
	((a++))
done
		
