#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:
#  displays 4 and then bad luck from China for the 4th loop iteration
#   displays 9 and then bad luck from Japan for the 9th loop iteration
#    displays 17 and then bad luck from Italy for the 17th loop iteration
#     using while loop and case statement

i=0

while [ $i -lt 20 ]
do
	case $i in

	"3")
		echo "bad luck from China"
		;;

	"8")
		echo "bad luck from Japan"
		;;
	"16")
		echo "bad luck from Italy"
		;;
	*)
		echo "Best School"
		;;
esac
(( i++ ))
done

