#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
#  display hours from 0 to 12
#  display minutes from 1 to 59
#   using a while loop

h=0
m=0

while [ $h -lt 13 ]
do
	if [ $m -eq 60 ] || [ $m -eq 0 ]
	then
		echo "Hour: $h"
		(( m=1 ))
		(( h++ ))
	else
		echo "$m"
		(( m++ ))
	fi
done
